SELECT
    COLUMN_NAME,
    ORDINAL_POSITION,
    IS_NULLABLE = CASE WHEN IS_NULLABLE = 'YES' THEN 1 ELSE 0 END,
    DATA_TYPE,
    COLUMN_DEFAULT
FROM tempdb.INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME LIKE @TableName + '%'
